# Cloudflare Pages configuration for Next.js
name = "remotechakri"
compatibility_date = "2023-06-06"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm install && node fix-edge-runtime.mjs && node fix-client-directives.mjs && npm run build"

# Output directory configuration
[site]
pages_build_output_dir = ".next/standalone"
assets_dir = ".next/static"

# Environment variables
[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://hdgnnxzanpbpbrboifem.supabase.co"
# Note: Sensitive variables like API keys should be set through Cloudflare dashboard

# Environment-specific configurations
[env.production]
name = "remotechakri-production"

[env.staging]
name = "remotechakri-staging"
